---
- name: Installer et démarrer Nginx sur les serveurs web
  hosts: serveur_web
  become: yes
  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present

    - name: Recharger le démon systemd pour prendre en compte la nouvelle unité de service
      command: systemctl daemon-reload

    - name: Démarrer et activer le service Nginx
      service:
        name: nginx
        state: started
        enabled: yes

- name: Installer et démarrer MariaDB sur les serveurs de bases de données
  hosts: serveur_db
  become: yes
  tasks:
    - name: Installer MariaDB Server
      apt:
        name: mariadb-server
        state: present

    - name: Démarrer et activer le service MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

