- name: Créer la base de données {{ database_name }}
  mysql_db:
    name: "{{ database_name }}"
    state: present
    login_user: root
    login_password: "MY_DB_ROOT_PASS"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes

- name: Créer l'utilisateur {{ database_user }} et lui accorder tous les privilèges sur {{ database_name }}
  mysql_user:
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    priv: "{{ database_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "MY_DB_ROOT_PASS"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes

